# Definicje wyjść (outputs) z modułu Terraform
# Te wartości są wyświetlane po pomyślnym wykonaniu `terraform apply`

output "frontend_url" {
  description = "Adres URL aplikacji frontendowej (React) hostowanej na CloudFront."
  value       = "https://${aws_cloudfront_distribution.s3_distribution.domain_name}"
}

output "cloudfront_distribution_id" {
  description = "ID dystrybucji CloudFront, potrzebne dla CI/CD."
  value       = aws_cloudfront_distribution.s3_distribution.id
}

output "backend_api_url" {
  description = "Adres URL API backendu (Django) dostępny przez Application Load Balancer."
  value       = "http://${aws_lb.main.dns_name}"
}

output "bastion_public_ip" {
  description = "Publiczny adres IP hosta bastionowego."
  value       = aws_instance.bastion.public_ip
}

output "ssh_command_to_bastion" {
  description = "Komenda SSH do połączenia z hostem bastionowym."
  value       = "ssh -i <sciezka_do_klucza_prywatnego> ec2-user@${aws_instance.bastion.public_ip}"
}

output "rds_endpoint" {
  description = "Endpoint bazy danych RDS MySQL."
  value       = aws_db_instance.main.endpoint
}

output "rds_db_name" {
  description = "Nazwa bazy danych RDS."
  value       = aws_db_instance.main.db_name
}

output "rds_db_password" {
  description = "Hasło do bazy danych RDS. Przechowywane jako 'sensitive'."
  value       = random_password.db_password.result
  sensitive   = true
}

output "s3_frontend_bucket_name" {
  description = "Nazwa bucketu S3 przechowującego build aplikacji React."
  value       = aws_s3_bucket.frontend.bucket
}

output "sns_topic_arn_for_alarms" {
  description = "ARN tematu SNS do subskrypcji w celu otrzymywania alertów."
  value       = aws_sns_topic.alarms.arn
}

output "django_secret_key" {
  description = "Django SECRET_KEY generated by Terraform. Przechowywane jako 'sensitive'."
  value       = random_password.django_secret.result
  sensitive   = true
}

output "rds_db_user" {
  description = "Użytkownik bazy danych RDS (login)"
  value       = aws_db_instance.main.username
  sensitive   = true
}

output "rds_host" {
  description = "Host RDS (endpoint, bez portu)"
  value       = aws_db_instance.main.address
}


